#spring.application.name=basic

# ⭐ .properties 파일 확장자 는 계층구조의 중복 발생
#   datasource.url=localhost:3306  /   datasource.driver-name=mariadb-driver  이런 형식

# ⭐ 대신 yml(와이엠엘), yaml(야물) 확장자 파일은 들여쓰기 계층구조 사용 가능
# 들여쓰기 중요!! 들여쓰기에 따라 안먹힘!
# 예시
#datasource.
#    url=localhost:3306
#    driver-name=mariadb-driver

# ⭐ 포트번호 변경 법 (default는 8080)  :: port가 자주 꼬이니 port kill을 진행해줘야한다
#server:
#  port: 8081

# ⭐ 정형화되어있는 코드
# github 업로드 시
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
